### PR TITLE
Update dcos launch

### PR DESCRIPTION
**Pull request by cprovencher**
https://jira.mesosphere.com/browse/DCOS-21660

### CODE REVIEW

**Comment by adamtheturtle** [comment]
Thank you @cprovencher !

This looks good to me but I'll leave it to @timaa2k, who knows this part of the code best, to review and merge this.

However, before doing that, please fix the lint issues - the first of which is:

```
flake8 .
+flake8 .
./src/dcos_e2e/backends/_aws/__init__.py:14:1: F401 'dcos_e2e._vendor.dcos_launch.aws.DcosCloudformationLauncher' imported but unused
./src/dcos_e2e/backends/_aws/__init__.py:15:1: F401 'dcos_e2e._vendor.dcos_launch.onprem.AbstractOnpremLauncher' imported but unused
```

See http://dcos-e2e.readthedocs.io/en/latest/contributing.html#linting for how to run the linters locally.

**Comment by adamtheturtle** [comment]
@cprovencher Please merge master in or rebase as we've fixed some CI flakiness since this was submitted.

**Comment by cprovencher** [comment]
@adamtheturtle 
do the dev requirements need to updated? I'm getting:
dcos 0.6.1 has requirement PyJWT==1.4.2, but you'll have pyjwt 1.6.1 which is incompatible.
dcoscli 0.6.1 has requirement cryptography==2.0.2, but you'll have cryptography 2.2.2 which is incompatible.

after running pip install --editable .[dev]

**Comment by adamtheturtle** [comment]
@cprovencher No they do not need to be updated. The CLI packages are used just in tests and they seem to work fine despite the incompatibilities.

**Comment by cprovencher** [comment]
@adamtheturtle looks like I had a linux-specific issue as dulwich requires gcc. Then dulwich would fail and none of the dependencies would build.... anyways I just installed except dulwich and now PR is updated.

**Comment by adamtheturtle** [comment]
Thanks - If you fancy writing that up as an issue I can hopefully document it. Let's see what happens with CI but I'm curious about the change to the file `admin/release.py` and I wonder if CI will fail on that.

**Comment by cprovencher** [comment]
the change to admin/release.py comes from "make fix-lint"

**Comment by adamtheturtle** [comment]
CI shows:

```
mypy *.py src/ tests/ admin/
+mypy setup.py versioneer.py src/ tests/ admin/
src/dcos_e2e/backends/_aws/__init__.py:210: note: unused 'type: ignore' comment
src/dcos_e2e/backends/_aws/__init__.py:216: note: unused 'type: ignore' comment
src/dcos_e2e/backends/_aws/__init__.py:243: note: unused 'type: ignore' comment
make: *** [mypy] Error 1
```

**Comment by adamtheturtle** [comment]
Great work!

**Pull request merged**
